# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
x = torch.rand(7, 7)
x

tensor([[0.8193, 0.5883, 0.8680, 0.9909, 0.4988, 0.4479, 0.1296],
        [0.2081, 0.1093, 0.0804, 0.0813, 0.9873, 0.8325, 0.7437],
        [0.4199, 0.5130, 0.5435, 0.6526, 0.4710, 0.8319, 0.4379],
        [0.6007, 0.7939, 0.9357, 0.7898, 0.3572, 0.9757, 0.7226],
        [0.7256, 0.8321, 0.5190, 0.9205, 0.7688, 0.2506, 0.4604],
        [0.6292, 0.2310, 0.5128, 0.4433, 0.8940, 0.3231, 0.4901],
        [0.1391, 0.7944, 0.9642, 0.0692, 0.7352, 0.7614, 0.4583]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
y = torch.rand(1, 7)
# Perform matrix multiplication 
z = torch.mm(x, y.T)
z.shape

torch.Size([7, 1])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [12]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
x = torch.rand(7, 7)
y = torch.rand(1, 7)
# Matrix multiply tensors
z = torch.mm(x, y.T)
print(z)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [7]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [10]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
print(torch.cuda.is_available())
# Create two random tensors on GPU
a = torch.rand(2, 3).to("cuda:0")
b = torch.rand(2, 3).to("cuda:0")
print(a)
print(b)

True
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [14]:
# Perform matmul on tensor_A and tensor_B
C = torch.mm(a, b.T)
print(C)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [16]:
# Find max
print(C.max())
# Find min
print(C.min())

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [17]:
# Find arg max
print(torch.argmax(C))

# Find arg min
print(torch.argmin(C))

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [18]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random_tensor = torch.rand(1, 1, 1, 10)

# Remove single dimensions
random_tensor_squeeze = random_tensor.squeeze()

# Print out tensors and their shapes
print(random_tensor, random_tensor.shape)
print(random_tensor_squeeze, random_tensor_squeeze.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
